version: '3.8'

services:
  # 1. ส่วนของ Database (MongoDB)
  mongo_db:
    image: mongo:latest
    container_name: Library-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. ส่วนของ Backend API
  backend_api:
    build: ./backend
    container_name: Library-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/Library-zeren

volumes:
  mongo_data:
